import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import PageHeader from '@/components/page.header'
import PageFooter from '@/components/page.footer'
import Container from 'react-bootstrap/Container';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = { title: 'Profile Page', description: 'Generated by vnbaodev' }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageHeader />
        <Container>
          {children}
        </Container>
        <PageFooter />
      </body>
    </html>
  )
}
