import React from 'react';

const PageFooter = () => {
    return (
        <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
            <div style={{ flex: 1 }}>
            </div>
            <div style={{ textAlign: "center", color: '#d6d6d6' }}>
                Generated by vnbaodev
            </div>
        </div>
    )
}

export default PageFooter;

